### ISSUE TITLE
User Story: Create functionality for user registration

### ISSUE THREAD

**Issue by markolejman** [markohautala/django-auth-crud-app#10]
As a **user** I want to **be able to create an account** so that **I can access the functions in the application**

## Acceptance Criteria

- AC 1: Given that I am on the application's sign-up page, when I fill out the required fields (such as username and password) and submit the form, then I should receive a confirmation message indicating successful account creation.
- AC 2: Given that I am on the application's sign-up page, when I try to submit the form without filling out all the required fields, then I should receive appropriate error messages highlighting the missing information.
- AC 3: Given that I am on the application's sign-up page, when I enter an username that is already associated with an existing account, then I should receive an error message notifying me that the name is already in use.

## Tasks

- [x] Create a question in the login.html that asks the user if they are new to the site and if they don't have an account yet, and after that there should be a anchor tag that the user can click on that redirects the user to the user registration page.
- [x] On the loginpage there should be the same as above but with the words "Do you already have an account" and after that there should be a link to the login-page.
- [x] In the class based views, create class and method so that when the user is succesfully created, the user should be logged in and redirected directly afterwards.
- [x] Add restriction so that a already logged in user cant access the login-page or the register page - if they type in that url then they are redirected to the "task-page" again.
