### ISSUE TITLE
User Story: Create a homepage / startpage

### ISSUE THREAD

**Issue by markolejman** [markohautala/django-auth-crud-app#14]
As a **user** I want to **land on a homepage** so that **I understand what the service/application is about**

## Acceptance Criteria

- AC 1: Given that a user accesses the website's root URL, when the homepage loads, then the user should see clear and informative content about the service/application.
- AC 2: Given that a user visits the homepage, when the page is displayed, then there should be prominent navigation elements such as login and register buttons visible.
- AC 3: Given that a user views the homepage, when exploring the content, then the layout should be structured using Bootstrap for a visually appealing and responsive design.

## Tasks

- [x] Create the URL in urls.py for "homepage" (home.html)
- [x] Create the class based view.
- [x] Add content to the homepage using Bootstrap.
- [x] When bootstrap items/components added, replace placeholder text with good information about the application
- [x] Add the login and register buttons to it aswell.
- [x] Add buttons "back to home" on all pages.
