### ISSUE TITLE
User Story: Enhancing User Experience: Completing Project, Optimizing Loading Speed, and Documenting in README

### ISSUE THREAD

**Issue by markolejman** [markohautala/django-auth-crud-app#15]
As a **user** I want to **be able to see the project as completed** so that **I can actually use the application and get the desired benefits from it**

## Acceptance Criteria

- AC 1: Given that I am logged into the application, when I navigate to the project details then I should be able to see a visual indicator that the project is marked as completed.
- AC 2: Given that I access the application when I navigate to any page within the application then the page should load within 2 seconds or less under normal network conditions.

## Tasks

- [x] Create the readme.md with all the required information about the project.
- [x] Get the CSS into static folder and remove it from the style-tag inside the main.hmtl file (makes loadup speed faster).
- [x] resolve xframe issue with am i responsive - add google chrome extension.
