### ISSUE TITLE
User Story: Setup models and database

### ISSUE THREAD

**Issue by markolejman** [markohautala/django-auth-crud-app#2]
As a **admin** I want **build out my database tables** so that **I can efficiently organize and manage data, leading to improved data integrity, faster query performance, and better overall system scalability**

## Acceptance Criteria

- AC 1: When creating a new table, the database should update to include it.
- AC 2: Adding a new column to a table should reflect in the database without data loss.
- AC 3: Deleting a table should remove it from the database along with its data.

## Tasks

- [x] Create the classes that represent the tables
- [x] Create the model columns or fields/attributes
- [x] Setup user authentication
- [x] Make migrations
- [x] create superuser to access django built-in admin-panel
- [x] register new models to admin panel
