### ISSUE TITLE
User Story: Create Items (CRUD-functionality)

### ISSUE THREAD

**Issue by markolejman** [markohautala/django-auth-crud-app#5]
As a **user** I want to **be able to create a task** so that **I can use the application and start working on my to-dos**

## Acceptance Criteria

- AC 1: When I click on the "Create Task" button, a new task form should appear.
- AC 2: After filling out the task details and clicking "Save", the task should be added to my list of todos.
- AC 3: Upon clicking on a specific task, I should be able to go back and view all the tasks again (see the whole list of tasks).
- 

## Tasks

- [x] Import Django CreateView
- [x] Create the actual view (class)
- [x] Set the correct redirect value (success_url/reverse_lazy)
- [x] create a back button to go back from a specific task to all the tasks
