### ISSUE TITLE
User Story: User Authentication and Signup/Login functionality

### ISSUE THREAD

**Issue by markolejman** [markohautala/django-auth-crud-app#8]
As a **user** I want to **be able to log in or sign up** so that **I can see or create items/to-dos**

## Acceptance Criteria

- AC 1: Given that I am not logged in, when I navigate to the website's login page, then I should see a login form with fields for username and password.
- AC 2: Given that I enter valid login credentials and submit the form, when the server verifies my credentials, then I should be redirected to the main dashboard where I can view my items/to-dos.
- AC 3: Given that I am not registered, when I navigate to the website's sign-up page, then I should see a registration form with fields for username, email, and password.

## Tasks

- [x] Add in a condition in the main-todo-list so that if a user is authenticated, then he/her can access that html.page. If not, then the user is prompted to register/sign-in.
- [x] Add conditional logic so that if user is authenticated, then log-out button is shown and if user is else but authenticated, then login/signup action is promted.
- [x] Import LoginView (auth) and add it to the top of the views.py because it is a gatekeeper for the rest of the views and functions.
- [x] Add template for login.html
- [x] In views.py redirects user to tasks page if already logged in and redirects user to tasks page after a successful login.
- [x] Import LoginView to urls.py and add the path there (on top)
- [x] Do the same for sign-out functionality. Import LogOut view to urls.py
- [x] Paste the logout link to the conditional logic in the "main-page". Route the urls.py in logout so that when user logs out then user is redirected to the login page again - good UX.
- [x] Once the user authentication is setup, then we need to add the functionality so that the to-dos become "invisible" or restricted if the user is not authenticated yet.
- [x] Add a route to where the user is redirected if the user is not authenticated.
- [x] Add LoginRequriedMixin wherever we want user authtentication and that restriction - for example for the class based views for add, edit and delete tasks - we want user authentication on all of them. Refactor views.py to include LoginRequiredMixin in all view classes.
