### ISSUE TITLE
User Story: User specific data for each user

### ISSUE THREAD

**Issue by markolejman** [markohautala/django-auth-crud-app#9]
As a **user** I want to **see only my created tasks** so that **I can work on my personal tasks**

## Acceptance Criteria

- AC 1: Given that a user is logged in, when accessing the task list view, then only tasks created by the logged-in user should be displayed.
- AC 2: Given that a user is logged in, when attempting to view details of a task, then only tasks created by the logged-in user should be accessible.
- AC 3: Given that a user is logged in, when creating a new task, that user can only create a task to themself.

## Tasks

- [x] Use the get_context_data method to only access the user specific data.
- [x] Use form_valid method to ensure that the user can only create a task for themself.
- [x] Change fields = "__all__" to ['title', 'description', 'complete']. This removes the possibility to user A to add or change tasks to user B - there is no field of changing user. By manually adding in the fields one by one instead of using __all__ we can control what fields the user can change and fill out.
